export const MALDIVES_ISLANDS: string[] = [
  // Kaafu (Malé) Atoll
  "Malé",
  "Hulhumalé",
  "Vilimalé",
  "Maafushi",
  "Guraidhoo",
  "Thulusdhoo",
  "Gulhi",
  "Himmafushi",
  "Huraa",
  "Kaashidhoo",
  "Dhiffushi",
  "Gaafaru",
  // Haa Alifu Atoll
  "Dhidhdhoo",
  "Kelaa",
  "Filladhoo",
  "Muraidhoo",
  "Uligamu",
  "Hoarafushi",
  "Thakandhoo",
  "Maarandhoo",
  "Vashafaru",
  "Ihavandhoo",
  "Baarah",
  "Molhadhoo",
  "Thuraakunu",
  // Haa Dhaal Atoll
  "Kulhudhuffushi",
  "Nolhivaram",
  "Hanimaadhoo",
  "Nolhivaranfaru",
  "Maavaidhoo",
  "Neykurendhoo",
  "Finey",
  "Nellaidhoo",
  "Kunburudhoo",
  "Vaikaradhoo",
  "Naivaadhoo",
  // Shaviyani Atoll
  "Funadhoo",
  "Komandoo",
  "Goidhoo",
  "Kanditheemu",
  "Foakaidhoo",
  "Maroshi",
  "Feevah",
  "Maakandoodhoo",
  "Lhaimagu",
  "Narudhoo",
  "Farikoodhuffaaru",
  "Billedhdhoo",
  "Maaungoohoo",
  // Noonu Atoll
  "Manadhoo",
  "Fodhdhoo",
  "Maafaru",
  "Holhudhoo",
  "Miladhoo",
  "Landhoo",
  "Velidhoo",
  "Kendhikulhudhoo",
  "Kudafariy",
  "Lhohi",
  "Magoodhoo",
  "Kedhikolhudhoo",
  // Raa Atoll
  "Ungoofaaru",
  "Rasgetheemu",
  "Alifushi",
  "Hulhudhuffaaru",
  "Maduvvari",
  "Vaadhoo",
  "Dhuvaafaru",
  "Fainu",
  "Meedhoo",
  "Rasmaadhoo",
  "Innamaadhoo",
  "Kinolhas",
  "Angolhitheemu",
  "Maakurathu",
  // Baa Atoll
  "Eydhafushi",
  "Dhonfanu",
  "Kendhoo",
  "Thulhaadhoo",
  "Fehendhoo",
  "Kihaadhuffaru",
  "Kudarikilu",
  "Maalhos",
  "Daravan",
  // Lhaviyani Atoll
  "Naifaru",
  "Hinnavaru",
  "Kurendhoo",
  "Olhuvelifushi",
  // Alifu Alifu (North Ari) Atoll
  "Rasdhoo",
  "Ukulhas",
  "Thoddoo",
  "Mathiveri",
  "Feridhoo",
  "Bodufolhudhoo",
  "Maalhos",
  // Alifu Dhaal (South Ari) Atoll
  "Mahibadhoo",
  "Dhangethi",
  "Maamigili",
  "Mandhoo",
  "Omadhoo",
  "Hangnameedhoo",
  "Dhigurah",
  "Himandhoo",
  "Fenfushi",
  // Vaavu (Felidhu) Atoll
  "Felidhoo",
  "Keyodhoo",
  "Fulidhoo",
  "Thinadhoo",
  "Rakeedhoo",
  // Meemu (Mulaku) Atoll
  "Muli",
  "Kolhufushi",
  "Dhiggaru",
  "Raimandhoo",
  "Madifushi",
  "Naalaafushi",
  "Veyvah",
  "Mulah",
  // Faafu (North Nilandhe) Atoll
  "Magoodhoo",
  "Nilandhoo",
  "Bilehdhoo",
  "Feeali",
  // Dhaalu (South Nilandhe) Atoll
  "Kudahuvadhoo",
  "Rinbudhoo",
  "Bandidhoo",
  "Hulhudheli",
  "Ribudhoo",
  "Velandhoo",
  // Thaa (Kolhumadulu) Atoll
  "Veymandoo",
  "Thimarafushi",
  "Buruni",
  "Vilifushi",
  "Gaadhiffushi",
  "Hirilandhoo",
  "Vandhoo",
  "Guraidhoo",
  "Kadhdhoo",
  "Kinbidhoo",
  // Laamu (Hadhdhunmathi) Atoll
  "Fonadhoo",
  "Maavah",
  "Mundoo",
  "Dhanbidhoo",
  "Kunahandhoo",
  "Maandhoo",
  "Isdhoo",
  "Kalaidhoo",
  "Hithadhoo",
  "Gan",
  "Kadhoo",
  "Gaadhoo",
  // Gaafu Alifu (North Huvadhu) Atoll
  "Viligili",
  "Kolamaafushi",
  "Dhaandhoo",
  "Gemanafushi",
  "Kondey",
  "Kanduhulhudhoo",
  "Maamendhoo",
  // Gaafu Dhaal (South Huvadhu) Atoll
  "Thinadhoo",
  "Madaveli",
  "Faresmaathodaa",
  "Hoandeddhoo",
  "Fiyoari",
  "Gadhdhoo",
  "Vaadhoo",
  "Rathafandhoo",
  // Gnaviyani Atoll
  "Fuvahmulah",
  // Seenu (Addu) Atoll
  "Addu City",
  "Hithadhoo",
  "Feydhoo",
  "Meedhoo",
  "Maradhoo",
  "Hulhumeedhoo",
].filter((v, i, a) => a.indexOf(v) === i).sort((a, b) => {
  // Keep Malé first
  if (a === "Malé") return -1;
  if (b === "Malé") return 1;
  return a.localeCompare(b);
});
